In [1]:
import pandas as pd

In [3]:
data = pd.read_csv(r'D:\Project 2026\AI\customer_support_rag\data\flipkart_product_review.csv')
data

,product_id,product_title,rating,summary,review
0,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,1-more flexible2-bass is very high3-sound clar...
1,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Super sound and good looking I like that prize
2,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,Very much satisfied with the device at this pr...
3,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,"Nice headphone, bass was very good and sound i..."
4,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Sound quality super battery backup super quali...
...,...,...,...,...,...
445,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,5,Wonderful,nice product.. color is exactly shown in the ...
446,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,5,Brilliant,Awesome Headset . I was searching for the same...
447,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,3,Fair,It's a really perfect earphone. I love it . So...
448,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,4,Value-for-money,Good earbuds at this price Range and Boat prov...
449,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,4,Wonderful,a very good earphone in budget sound is awesom...

In [4]:
data['review'][0]

"1-more flexible2-bass is very high3-sound clarity is good 4-battery back up to 6 to 8 hour's 5-main thing is fastest charging system is available in that. Only 20 min charge and get long up to 4 hours back up 6-killing look awesome 7-for gaming that product does not support 100% if you want for gaming then I'll recommend you please don't buy but you want for only music then this product is very well for you.. 8-no more wireless headphones are comparing with that headphones at this pric..."

In [5]:
data

,product_id,product_title,rating,summary,review
0,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,1-more flexible2-bass is very high3-sound clar...
1,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Super sound and good looking I like that prize
2,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,Very much satisfied with the device at this pr...
3,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Super!,"Nice headphone, bass was very good and sound i..."
4,ACCFZGAQJGYCYDCM,BoAt Rockerz 235v2 with ASAP charging Version ...,5,Terrific purchase,Sound quality super battery backup super quali...
...,...,...,...,...,...
445,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,5,Wonderful,nice product.. color is exactly shown in the ...
446,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,5,Brilliant,Awesome Headset . I was searching for the same...
447,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,3,Fair,It's a really perfect earphone. I love it . So...
448,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,4,Value-for-money,Good earbuds at this price Range and Boat prov...
449,ACCEVQZABYWJHRHF,BoAt BassHeads 100 Wired Headset,4,Wonderful,a very good earphone in budget sound is awesom...